"""
Django settings for samplesite project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import STATICFILES_DIRS, ABSOLUTE_URL_OVERRIDES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t^rz5=#sklw9y1b%bk49wu-1j_&hiehcu3(@f-_pz(-arkk1)m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'captcha',
    'precise_bbcode',
    'django_bootstrap5',
    'django_cleanup',
    'easy_thumbnails',

    'bboard',  # 'bboard.apps.BboardConfig',
    'testapp',
    'api',
    
    # 'todolist',
    'rest_framework',
    'corsheaders',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# AUTH_USER_MODEL = 'testapp.models.AdvUser'

ROOT_URLCONF = 'samplesite.urls'

# LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = None

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 'libraries': {
            #     # 'bbtags': 'bboard.bbtags',
            #     'tg': 'bboard.bbtags',
            # },
            # 'builtins': [         # load не будет нужен
            #     'bboard.bbtags',
            # ],
        },
    },
]

WSGI_APPLICATION = 'samplesite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',

        # 'ATOMIC_REQUESTS': False,  # по умолчанию, каждая операция в отдельной транзакции
        # 'ATOMIC_REQUESTS': True,   # атомарные запросы, все операции в одной транезакции
        # 'AUTOCOMMIT': True,        # по умолчанию, автоматическое завершение транзакций
    }
    # "default": {
    #     "ENGINE": "django.db.backends.postgresql",
    #     "NAME": "django_db",
    #     "USER": "django_user",
    #     "PASSWORD": "1234",
    #     "HOST": "127.0.0.1",
    #     "PORT": "5432",
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
# STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ABSOLUTE_URL_OVERRIDES = {
#     'bboard.rubric': lambda rec: f"{rec.pk}/"
# }

DEFAULT_CHARSET = 'utf-8'


""" django-simple-captcha """

# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.word_challenge'
#
# CAPTCHA_WORDS_DICTIONARY = BASE_DIR / 'static/words.txt'
# CAPTCHA_DICTIONARY_MIN_LENGTH = 0
# CAPTCHA_DICTIONARY_MAX_LENGTH = 99

# CAPTCHA_TIMEOUT = 5

# CAPTCHA_LENGTH = 4
# CAPTCHA_LENGTH = 6

# CAPTCHA_MATH_CHALLENGE_OPERATOR = '*'
# CAPTCHA_MATH_CHALLENGE_OPERATOR = 'x'

# CAPTCHA_FONT_SIZE = 22
# CAPTCHA_LETTER_ROTATION = (-35, 35)

# CAPTCHA_BACKGROUND_COLOR = "#001100"
# CAPTCHA_FOREGROUND_COLOR = "#ffffff"

# CAPTCHA_IMAGE_SIZE = (200, 100)

"""
BBCode
"""

BBCODE_NEWLINE = "<br>"
# BBCODE_DISABLE_BUILTIN_TAGS = False
# BBCODE_ALLOW_CUSTOM_TAGS = True

BBCODE_ALLOW_SMILIES = True
# SMILIES_UPLOAD_TO = 'precise_bbcode/smilies'


BOOTSTRAP5 = {
    'required_css_class': 'required',
    'success_css_class': 'has-success',
    'error_css_class': 'has-error',
}


#############
### FILES ###
#############
# FILE_UPLOAD_MAX_MEMORY_SIZE = 2_621_440  # 2.5 Mb
# FILE_UPLOAD_TEMP_DIR = None
# FILE_UPLOAD_PERMISSIONS = None  # 0o644
# FILE_UPLOAD_DIRECTORY_PERMISSIONS = None  # 0o600
# DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'


##################
### THUMBNAILS ###
##################

THUMBNAIL_ALIASES = {
    'bboard.Bb.picture': {
        'default': {
            'size': (500, 300),
            'crop': 'scale',
        },
    },
    # 'testapp': {
    'bboard': {
        'default': {
            'size': (400, 300),
            'crop': 'smart',
            'bw': True,
        },
    },
    '': {
        'default': {
            'size': (180, 240),
            'crop': 'scale',
        },
        'big': {
            'size': (480, 640),
            'crop': '10,10',
        }
    }
}

# THUMBNAIL_DEFAULT_OPTIONS = {
#     'quality': 90,
#     'subsampling': 1,
# }

THUMBNAIL_MEDIA_URL = '/thumbs/'
THUMBNAIL_MEDIA_ROOT = BASE_DIR / 'media/thumbs'
THUMBNAIL_BASEDIR = "thumbs"
THUMBNAIL_PREFIX = "thumb_"
# THUMBNAIL_EXTENSION = 'jpg'
# THUMBNAIL_TRANSPARENCY_EXTENSION = 'png'


################
### SESSIONS ###
################
# SESSION_ENGINE = "django.contrib.sessions.backends.db"  # по умолчанию
# SESSION_ENGINE = "django.contrib.sessions.backends.file"
# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
# SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

##################
#####  EMAILS ####
##################
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# DEFAULT_FROM_EMAIL = 'webmaster@localhost'

# EMAIL_HOST = 'localhost'
# EMAIL_PORT = 25
# EMAIL_HOST_EMAIL = ''
# EMAIL_HOST_PASSWORD = ''
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = True
# EMAIL_SSL_CERTFILE = None
# EMAIL_SSL_KEYFILE = None
# EMAIL_TIMEOUT = None

# EMAIL_FILE_PATH = ''


ADMINS = [
    ('Admin1', 'admin1@mail.ru'),
    ('Admin2', 'admin2@mail.ru'),
    ('Admin3', 'admin3@mail.ru'),
]



#############################
#### Настройка для GMAIL #####
#############################

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'lioleg1402@gmail.com'
EMAIL_HOST_PASSWORD = 'wibq bmbb gtcf ftck'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


################################
###### CORSHEADERS SETTINGS ####
################################

CORS_ALLOWED_ALL_ORIGINS = True

CORS_URLS_REGEX = r'^/api/.*$'

CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:5500',
]

# CORS_ALLOWED_ORIGINS = [
#     'http://www.bboard.kz',
#     'https://www.bboard.kz',
#     'http://admin.bboard.kz',
# ]

# CORS_ALLOWED_ORIGINS_REGEX = [
#     r'^https?://(www|admin)\.bboard.kz$',
#     r'^http?://(www\.)?bb\.net$',
    
# ]

# CORS_ALLOWED_METHODS = ['GET', 'POST']



################################
##### DJANGO REST FRAMEWORK ####
################################
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
            'rest_framework.permissions.AllowAny',
            # 'rest_framework.permissions.IsAuthenticated',
            # 'rest_framework.permissions.IsAuthenticatedOrReadOnly',
            # 'rest_framework.permissions.IsAdminUser',
            # 'rest_framework.permissions.DjangoModelPermissions',
            # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',

        ),
}