# Generated by Django 5.2 on 2025-05-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_message_options_alter_privatemessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='spares',
            field=models.ManyToManyField(through='testapp.Kit', through_fields=('machine', 'spare'), to='testapp.spare'),
        ),
    ]
